version: "3.1"

services:
  http:
    build: .
    restart: always
    container_name: florence-api
    links:
      - mongodb
    ports:
      - 8080:8080
    working_dir: /opt/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - $HOME/data/springboot-mongo-data:/data/db
      - $HOME/data/springboot-mongo-bkp:/data/bkp
    restart: always